"""Render segfix's icons out as image files.

The icons are drawn with QPainter at runtime (see :mod:`segfix.icons`), which
keeps them crisp at any DPI but leaves nothing on disk for a README, a
desktop entry or a Windows installer to point at. This renders the very same
draw functions to files, so the exported set cannot drift from what the
buttons actually show — change an icon in the code and re-run this.

    python scripts/export_icons.py [--out assets/icons] [--light]

Writes, under the output folder:

* ``png/<name>-<size>.png`` — every button icon at each size in SIZES
* ``svg/<name>.svg``        — the same, as vector
* ``segfix.ico``            — the app icon, every size in one file, for the
                              Windows build and installer
* ``segfix-<size>.png``, ``segfix.svg`` — the app icon on its own

``--light`` re-points the neutral stroke (``icons.FG``, a pale grey chosen
for the dark theme) at a dark one, for placing on a white background. The
accent colours the icons use for emphasis — green, red, blue, amber — are
left alone, since flattening those would lose what they mark.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

#: Button icons are drawn in a 32x32 coordinate space; these are the pixel
#: sizes to render that into. 16-48 cover toolbars and menus at 1x-2x, 128
#: and 256 are for documentation and the installer.
SIZES = (16, 24, 32, 48, 64, 128, 256)

#: The coordinate space segfix.icons draws its button icons in.
CANVAS = 32

LIGHT_STROKE = "#303030"


def _render_png(draw, size: int, path: Path) -> None:
    from qtpy.QtCore import Qt
    from qtpy.QtGui import QPainter, QPixmap

    from segfix import icons

    pix = QPixmap(size, size)
    # Drawing happens in CANVAS units whatever the pixel size, so the device
    # pixel ratio does the scaling — exactly as icons.icon() does it.
    pix.setDevicePixelRatio(size / CANVAS)
    pix.fill(Qt.transparent)
    painter = QPainter(pix)
    painter.setRenderHint(QPainter.Antialiasing)
    painter.setPen(icons._pen())
    painter.setBrush(Qt.NoBrush)
    draw(painter)
    painter.end()
    pix.save(str(path), "PNG")


def _render_svg(draw, path: Path) -> None:
    from qtpy.QtCore import QSize, Qt
    from qtpy.QtGui import QPainter
    from qtpy.QtSvg import QSvgGenerator

    from segfix import icons

    generator = QSvgGenerator()
    generator.setFileName(str(path))
    generator.setSize(QSize(CANVAS, CANVAS))
    generator.setViewBox(generator.viewBox().adjusted(0, 0, CANVAS, CANVAS))
    generator.setTitle(path.stem)
    generator.setDescription("Generated by scripts/export_icons.py")
    painter = QPainter(generator)
    painter.setRenderHint(QPainter.Antialiasing)
    painter.setPen(icons._pen())
    painter.setBrush(Qt.NoBrush)
    draw(painter)
    painter.end()


def _write_ico(path: Path, sizes=SIZES) -> None:
    """The app icon as one multi-resolution .ico.

    Qt's image writer puts a single image in a file, and a Windows shortcut
    wants every size in one — so the container is assembled here. Each entry
    holds a PNG, which Windows has accepted inside .ico since Vista and which
    keeps the file small. icons.app_icon() already draws at each size, so
    these are its own pixmaps rather than one scaled down.
    """
    import struct

    from qtpy.QtCore import QBuffer, QByteArray, QIODevice

    from segfix import icons

    app = icons.app_icon()
    blobs = []
    for size in sizes:
        data = QByteArray()
        buffer = QBuffer(data)
        buffer.open(QIODevice.OpenModeFlag.WriteOnly)
        app.pixmap(size, size).save(buffer, "PNG")
        buffer.close()
        blobs.append((size, bytes(data)))

    header = struct.pack("<HHH", 0, 1, len(blobs))
    offset = len(header) + 16 * len(blobs)
    entries, payload = [], []
    for size, blob in blobs:
        entries.append(struct.pack(
            "<BBBBHHII",
            size if size < 256 else 0,   # 0 means 256 in an icon directory
            size if size < 256 else 0,
            0, 0, 1, 32, len(blob), offset,
        ))
        payload.append(blob)
        offset += len(blob)
    path.write_bytes(header + b"".join(entries) + b"".join(payload))


def _write_app_pngs(folder: Path, sizes=SIZES) -> None:
    from segfix import icons

    app = icons.app_icon()
    for size in sizes:
        app.pixmap(size, size).save(str(folder / f"segfix-{size}.png"), "PNG")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--out", default="assets/icons", type=Path,
        help="folder to write into (default: assets/icons)",
    )
    parser.add_argument(
        "--light", action="store_true",
        help="dark neutral stroke, for placing on a light background",
    )
    args = parser.parse_args(argv)

    from qtpy.QtGui import QColor, QGuiApplication

    app = QGuiApplication.instance() or QGuiApplication([])

    from segfix import icons

    if args.light:
        icons.FG = QColor(LIGHT_STROKE)

    out = args.out
    (out / "png").mkdir(parents=True, exist_ok=True)
    (out / "svg").mkdir(parents=True, exist_ok=True)

    for name, draw in sorted(icons._DRAW.items()):
        for size in SIZES:
            _render_png(draw, size, out / "png" / f"{name}-{size}.png")
        _render_svg(draw, out / "svg" / f"{name}.svg")

    _write_ico(out / "segfix.ico")
    _write_app_pngs(out)

    written = sum(1 for _ in out.rglob("*") if _.is_file())
    print(
        f"{len(icons._DRAW)} button icons at {len(SIZES)} sizes, plus SVG and "
        f"the app icon: {written} files under {out}"
    )
    _ = app
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
